---
title: "Untitled"
author: "Connor Flynn"
date: "7/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(readxl)
library(xlsx)
library(ClustImpute)
library(tidyverse)
library(cluster)
library(factoextra)
library(gridExtra)
options(scipen = 99)
```

Goal 1


Import data
```{r}
goal1 <- read_csv(here("data/sdg_data/Goal1.csv"))

```

```{r}
goal1_male <- goal1 %>% 
  filter(Sex == "MALE")

goal1_female <- goal1 %>% 
  filter(Sex == "FEMALE")

goal1_bothsex <- goal1 %>% 
  filter(Sex == "BOTHSEX")

goal1_urban <- goal1 %>% 
  filter(Location == "URBAN")

goal1_rural <- goal1 %>% 
  filter(Location == "RURAL")

goal1_allarea <- goal1 %>% 
  filter(Location == "ALLAREA")

```


```{r}
goal1_2005 <- goal1 %>% 
  filter(TimePeriod == "2005")

goal1_2005_tidy_grouped <- goal1_2005 %>% 
  group_by(SeriesDescription, GeoAreaName) %>% 
  summarise(MedianValue = median(Value))


goal1_2005_wider <- goal1_2005_tidy_grouped %>% 
  pivot_wider(names_from = SeriesDescription,
              values_from = MedianValue)

goal1_2006 <- goal1 %>% 
  filter(TimePeriod == "2006")

goal1_2007 <- goal1 %>% 
  filter(TimePeriod == "2007")

goal1_2008 <- goal1 %>% 
  filter(TimePeriod == "2008")

goal1_2009 <- goal1 %>% 
  filter(TimePeriod == "2009")

goal1_2010 <- goal1 %>% 
  filter(TimePeriod == "2010")

goal1_2010 <- goal1 %>% 
  filter(TimePeriod == "2010")

goal1_2011 <- goal1 %>% 
  filter(TimePeriod == "2011")

goal1_2012 <- goal1 %>% 
  filter(TimePeriod == "2012")

goal1_2013 <- goal1 %>% 
  filter(TimePeriod == "2013")

goal1_2014 <- goal1 %>% 
  filter(TimePeriod == "2014")

goal1_2015 <- goal1 %>% 
  filter(TimePeriod == "2015")

goal1_2016 <- goal1 %>% 
  filter(TimePeriod == "2016")

goal1_2017 <- goal1 %>% 
  filter(TimePeriod == "2017")

goal1_2018 <- goal1 %>% 
  filter(TimePeriod == "2018")

goal1_2019 <- goal1 %>% 
  filter(TimePeriod == "2019")

goal1_2020 <- goal1 %>% 
  filter(TimePeriod == "2020")

goal1_2021 <- goal1 %>% 
  filter(TimePeriod == "2021")





```

