---
title: "missRanger"
author: "Connor Flynn"
date: "7/13/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(missRanger)
library(here)
library(janitor)
library(cluster)
library(factoextra)
library(randomForest)
options(scipen = 99)
options(ggrepel.max.overlaps = Inf)
```

```{r}
sdg_indicators <- read_csv(here("data/sdg_data/sdg_indicators.csv"))
```
```{r}
sdg_indicators<- sdg_indicators %>% 
  filter(geo_area_name != "Cuba",
         geo_area_name != "Singapore")
```



```{r}
sdg_indicators <- sdg_indicators %>% 
  remove_rownames %>% 
  column_to_rownames(var="geo_area_name")
```




```{r}
sdg_indicators_less_na <- sdg_indicators[, which(colMeans(!is.na(sdg_indicators)) > 0.4)]
```

```{r}
sdg_indicators_missRanger <- missRanger(sdg_indicators_less_na, 
                                        formula = . ~ ., 
                                        num.trees = 1000,
                                        seed = 3,
                                        returnOOB = TRUE
                                      )
```


```{r}
sdg_indicators_missRanger
```


Remove columns with 0 variance

```{r}
sdg_indicators_missRanger_no_variance <- sdg_indicators_missRanger[, sapply(sdg_indicators_missRanger, var) != 0]
```




create visualization to decide appropriate \# of clusters for kmeans function

```{r}
fviz_nbclust(sdg_indicators_missRanger_no_variance, kmeans, method = "wss")
```

```{r}
set.seed(3)
kmeans2 <- kmeans(sdg_indicators_missRanger_no_variance, center = 5, nstart = 100)
```

```{r}
fviz_cluster(kmeans2, data = sdg_indicators_missRanger_no_variance,
geom = c("text","point"),
             repel = TRUE,            # Avoid label overlapping
             show.clust.cent = TRUE, # Show cluster centers
             palette = "lancet",         # Color palette see ?ggpubr::ggpar
             ggtheme = theme_bw()+
              theme(axis.text.x = element_text( hjust = 0.5, vjust = 0.5, size=15),
        axis.title.x =element_text(size=20),
        axis.text.y = element_text(hjust = 0.5, vjust = 0.5, size=15),
        axis.title.y =element_text(size=20),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"),
        strip.text = element_text(size=25)))
```


True vs Imputed Plots

```{r}
ggplot(data = sdg_indicators_missRanger_no_variance, aes(y = rownames(sdg_indicators_missRanger_no_variance), 
                                            x =  proportion_of_population_below_international_poverty_line_percent,
                                            fill = rownames(sdg_indicators_missRanger_no_variance))) +
  geom_col(show.legend = FALSE) + 
  scale_fill_manual(values = c(Anguilla = "blue",  
                               Belize = "blue",
                               Cook_Islands = "blue",       
                               Palau = "blue",
                               Puerto_Rico = "blue",   
                               Suriname = "blue",
                               Trinidad_and_Tobago = "blue",
                               United_States_Virgin_Islands = "blue",
                               Aruba = "blue",
                               Bahamas = "blue",
                               Barbados = "blue",
                               British_Virgin_Islands = "blue",
                               Dominica = "blue", 
                               Grenada = "blue", 
                               Guyana = "blue",
                               Saint_Vincent_and_the_Grenadines = "blue",
                               Antigua_and_Barbuda = "blue",
                               Saint_Kitts_and_Nevis = "blue",              
                               Curaçao = "blue",
                               New_Caledonia = "blue",
                               "Sint_Maarten_(Dutch_part)" = "blue",           
                               American_Samoa = "blue",
                               French_Polynesia = "blue",            
                               Guam = "blue",
                               Niue         = "blue",
                               Northern_Mariana_Islands = "blue",              
                               Montserrat = "blue"))
```



Goal 13

```{r}
goal13_na_example <- row.names(sdg_indicators)[which(is.na(sdg_indicators$number_of_directly_affected_persons_attributed_to_disasters_per_100_000_population_number))]

cat(paste(goal13_na_example),sep=",")

```



```{r}
ggplot(data = sdg_indicators_missRanger_no_variance, aes(y = rownames(sdg_indicators_missRanger_no_variance), 
                                            x =  number_of_directly_affected_persons_attributed_to_disasters_per_100_000_population_number,
                                            fill = rownames(sdg_indicators_missRanger_no_variance))) +
  geom_col(show.legend = FALSE)  +
  scale_fill_manual(values = c(Anguilla = "blue",
                               Dominican_Republic = "blue",
                               Haiti = "blue",
                               Puerto_Rico = "blue",
                               Suriname = "blue",
                               United_States_Virgin_Islands = "blue",
                               Aruba = "blue",
                               Bahamas = "blue",
                               British_Virgin_Islands = "blue",
                               Sao_Tome_and_Principe = "blue",
                               Curaçao = "blue",
                               Nauru = "blue",
                               'Sint_Maarten_(Dutch_part)' = "blue",
                               Montserrat = "blue"))




```

Goal 3

```{r}
goal3_na_example <- row.names(sdg_indicators)[which(is.na(sdg_indicators$crude_death_rate_attributed_to_household_and_ambient_air_pollution_deaths_per_100_000_population))]

cat(paste(goal3_na_example),sep=",")

```

```{r}
ggplot(data = sdg_indicators_missRanger_no_variance, aes(y = rownames(sdg_indicators_missRanger_no_variance), 
                                            x =  crude_death_rate_attributed_to_household_and_ambient_air_pollution_deaths_per_100_000_population,
                                            fill = rownames(sdg_indicators_missRanger_no_variance))) +
  geom_col(show.legend = FALSE)  +
  scale_fill_manual(values = c(Anguilla = "blue",
                               Cook_Islands = "blue",
                               Palau = "blue",
                               Puerto_Rico = "blue",
                               United_States_Virgin_Islands = "blue",
                               Aruba = "blue",
                               British_Virgin_Islands = "blue",
                               Dominica = "blue",
                               Saint_Kitts_and_Nevis = "blue",
                               Curaçao = "blue",
                               Marshall_Islands = "blue",
                               Nauru = "blue",
                               Tuvalu = "blue",
                               New_Caledonia = "blue",
                               "Sint_Maarten_(Dutch_part)" = "blue",
                               American_Samoa = "blue",
                               French_Polynesia = "blue",
                               Guam = "blue",
                               Niue = "blue",
                               Northern_Mariana_Islands = "blue",
                               Montserrat = "blue"))
```



Goal 4 

```{r}
goal4_na_example <- row.names(sdg_indicators)[which(is.na(sdg_indicators$proportion_of_schools_with_access_to_computers_for_pedagogical_purposes_by_education_level_percent))]

cat(paste(goal4_na_example),sep=",")
```


```{r}
ggplot(data = sdg_indicators_missRanger_no_variance, aes(y = rownames(sdg_indicators_missRanger_no_variance), 
                                            x =  proportion_of_schools_with_access_to_computers_for_pedagogical_purposes_by_education_level_percent,
                                            fill = rownames(sdg_indicators_missRanger_no_variance))) +
  geom_col(show.legend = FALSE)  +
  scale_fill_manual(values = c(Belize = "blue",
                               Dominican_Republic = "blue",
                               Fiji = "blue",
                               Haiti = "blue",
                               'Micronesia_(Federated_States_of)' = "blue",
                               Puerto_Rico = "blue",
                               Suriname = "blue",
                               'Timor-Leste' = "blue",
                               Trinidad_and_Tobago = "blue",
                               United_States_Virgin_Islands = "blue",
                               Vanuatu = "blue",
                               Bahamas = "blue",
                               Barbados = "blue",
                               Guyana = "blue",
                               Papua_New_Guinea = "blue",
                               Curaçao = "blue",
                              'Guinea-Bissau' = "blue",
                               New_Caledonia = "blue",
                               American_Samoa = "blue",
                               French_Polynesia = "blue",
                               Guam = "blue",
                               Northern_Mariana_Islands = "blue"))
```


Goal 7

```{r}
goal7_na_example <- row.names(sdg_indicators)[which(is.na(sdg_indicators$proportion_of_population_with_access_to_electricity_by_urban_rural_percent))]

cat(paste(goal7_na_example),sep=",")
```



```{r}
ggplot(data = sdg_indicators_missRanger_no_variance, aes(y = rownames(sdg_indicators_missRanger_no_variance), 
                                            x =  proportion_of_population_with_access_to_electricity_by_urban_rural_percent,
                                            fill = rownames(sdg_indicators_missRanger_no_variance))) +
  geom_col(show.legend = FALSE)  +
  scale_fill_manual(values = c(American_Samoa = "blue",
                               Montserrat = "blue"))
```








```{r}
as.data.frame(sdg_indicators_missRanger_no_variance$age_standardized_mortality_rate_attributed_to_household_air_pollution_deaths_per_100_000_population)
```

```{r}
ggplot() + 
  geom_point(data = sdg_indicators_missRanger_no_variance, aes(y = rownames(sdg_indicators_missRanger_no_variance),
                                        x = age_standardized_mortality_rate_attributed_to_household_air_pollution_deaths_per_100_000_population),
             color = "black") + 
  theme_minimal()

ggplot() +
  geom_point(data = sdg_indicators, aes(y = rownames(sdg_indicators),
                                        x = age_standardized_mortality_rate_attributed_to_household_air_pollution_deaths_per_100_000_population),
             color = "black") +
  theme_minimal()
```

```{r}
ggplot() + 
  geom_point(data = sdg_indicators_missRanger_no_variance, aes(y = rownames(sdg_indicators_missRanger_no_variance),
                                        x = proportion_of_population_with_access_to_electricity_by_urban_rural_percent),
             color = "black") + 
  theme_minimal()

ggplot() +
  geom_point(data = sdg_indicators, aes(y = rownames(sdg_indicators),
                                        x = proportion_of_population_with_access_to_electricity_by_urban_rural_percent),
             color = "black") +
  theme_minimal()
```
```{r}
ggplot() + 
  geom_point(data = sdg_indicators_missRanger_no_variance, aes(y = rownames(sdg_indicators_missRanger_no_variance),
                                        x = proportion_of_population_with_access_to_electricity_by_urban_rural_percent),
             color = "black") + 
  theme_minimal()

ggplot() +
  geom_point(data = sdg_indicators, aes(y = rownames(sdg_indicators),
                                        x = proportion_of_population_with_access_to_electricity_by_urban_rural_percent),
             color = "black") +
  theme_minimal()
```


Random Forest


```{r}
miss_Ranger_rf_international_poverty <- randomForest(proportion_of_population_below_international_poverty_line_percent ~ ., data = sdg_indicators_missRanger_no_variance, 
                   importance = TRUE)
```

```{r}
miss_Ranger_rf_international_poverty
```

```{r}
ImpData_international_poverty <- as.data.frame(importance(miss_Ranger_rf_international_poverty))
ImpData_international_poverty$Var.Names <- row.names(ImpData_international_poverty)
# 
# ggplot(ImpData, aes(x=Var.Names, y=`%IncMSE`)) +
#   geom_segment( aes(x=Var.Names, xend=Var.Names, y=0, yend=`%IncMSE`), color="skyblue") +
#   geom_point(aes(size = IncNodePurity), color="blue", alpha=0.6) +
#   theme_light() +
#   coord_flip() +
#   theme(
#     legend.position="bottom",
#     panel.grid.major.y = element_blank(),
#     panel.border = element_blank(),
#     axis.ticks.y = element_blank()
#   )

View(ImpData_international_poverty)

names(ImpData_international_poverty)[names(ImpData_international_poverty) == '%IncMSE'] <- 'per_inc_mse'


ImpData_international_poverty_highest_mse <- ImpData_international_poverty %>% 
  slice_max(per_inc_mse, n = 15)
```


