---
title: "tidy_test"
author: "Connor Flynn"
date: "6/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(readxl)

library(tidyverse)
library(cluster)
library(factoextra)
library(gridExtra)
options(scipen = 99)
```



Import data
```{r}
goal1 <- read_xlsx(here("data/sdg_data/Goal1.xlsx"))

```

Convert Value Column to class numeric
```{r}
goal1 <- goal1 %>% 
  mutate(Value = as.numeric(Value))
```


Group in order to get median value form multiple years/categories of data
```{r}
# goal1_tidy <- goal1 %>% 
#   filter(Location == "ALLAREA" & Age == "ALLAGE" & Sex == "BOTHSEX")
  


goal1_tidy_grouped <- goal1 %>% 
  group_by(SeriesDescription, GeoAreaName) %>% 
  summarise(MedianValue = median(Value))
```

```{r}
goal1_wider <- goal1_tidy_grouped %>% 
  pivot_wider(names_from = SeriesDescription,
              values_from = MedianValue)
```

```{r}
bahamas_test <- goal1 %>% 
  filter(GeoAreaName == "Bahamas" & SeriesCode == "SD_XPD_ESED")


fiji_test <- goal1 %>% 
  filter(GeoAreaName == "Fiji" & SeriesCode == "DC_ODA_POVLG")

guam_test <- goal1 %>% 
  filter(GeoAreaName == "Guam")
```

```{r}
kmeans2 <- kmeans(goal1_wider, centers = 2, nstart = 25)
```

NA's

```{r}
na_rows = rowSums(is.na(goal1_wider))

which(na_rows >40)
```

