---
title: "data"
author: "Connor Flynn"
date: "7/26/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#load libraries
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}

librarian::shelf(tidyverse,
                here,
                viridis,
                plotly)

options(scipen = 99)
```

Load in all data 

```{r}
goal1 <- read_csv(here("data/sdg_data/Goal1.csv"))
goal2 <- read_csv(here("data/sdg_data/Goal2.csv"))
goal3 <- read_csv(here("data/sdg_data/Goal3.csv"))
goal4 <- read_csv(here("data/sdg_data/Goal4.csv"))
goal5 <- read_csv(here("data/sdg_data/Goal5.csv"))
goal6 <- read_csv(here("data/sdg_data/Goal6.csv"))
goal7 <- read_csv(here("data/sdg_data/Goal7.csv"))
goal8 <- read_csv(here("data/sdg_data/Goal8.csv"))
goal9 <- read_csv(here("data/sdg_data/Goal9.csv"))
goal10 <- read_csv(here("data/sdg_data/Goal10.csv"))
goal11 <- read_csv(here("data/sdg_data/Goal11.csv"))
goal12 <- read_csv(here("data/sdg_data/Goal12.csv"))
goal13 <- read_csv(here("data/sdg_data/Goal13.csv"))
goal14 <- read_csv(here("data/sdg_data/Goal14.csv"))
goal15 <- read_csv(here("data/sdg_data/Goal15.csv"))
goal16 <- read_csv(here("data/sdg_data/Goal16.csv"))
goal17 <- read_csv(here("data/sdg_data/Goal17.csv"))

```

```{r}
goal1 <- goal1 %>% 
  select(GeoAreaName, SeriesDescription, TimePeriod, Value)

goal2 <- goal2 %>% 
  select(GeoAreaName, SeriesDescription, TimePeriod, Value) %>% 
  mutate(Value = as.numeric(Value))

goal3 <- goal3 %>% 
  select(GeoAreaName, SeriesDescription, TimePeriod, Value) %>% 
  mutate(Value = as.numeric(Value))

goal4 <- goal4 %>% 
  select(GeoAreaName, SeriesDescription, TimePeriod, Value) %>% 
  mutate(Value = as.numeric(Value))

goal5 <- goal5 %>% 
  select(GeoAreaName, SeriesDescription, TimePeriod, Value) %>% 
  mutate(Value = as.numeric(Value))

goal6 <- goal6 %>% 
  select(GeoAreaName, SeriesDescription, TimePeriod, Value) %>% 
  mutate(Value = as.numeric(Value))

goal7 <- goal7 %>% 
  select(GeoAreaName, SeriesDescription, TimePeriod, Value) %>% 
  mutate(Value = as.numeric(Value))

goal8 <- goal8 %>% 
  select(GeoAreaName, SeriesDescription, TimePeriod, Value) %>% 
  mutate(Value = as.numeric(Value))

goal9 <- goal9 %>% 
  select(GeoAreaName, SeriesDescription, TimePeriod, Value) %>% 
  mutate(Value = as.numeric(Value))

goal10 <- goal10 %>% 
  select(GeoAreaName, SeriesDescription, TimePeriod, Value) %>% 
  mutate(Value = as.numeric(Value))

goal11 <- goal11 %>% 
  select(GeoAreaName, SeriesDescription, TimePeriod, Value) %>% 
  mutate(Value = as.numeric(Value))

goal12 <- goal12 %>% 
  select(GeoAreaName, SeriesDescription, TimePeriod, Value) %>% 
  mutate(Value = as.numeric(Value))

goal13 <- goal13 %>% 
  select(GeoAreaName, SeriesDescription, TimePeriod, Value) %>% 
  mutate(Value = as.numeric(Value))

goal14 <- goal14 %>% 
  select(GeoAreaName, SeriesDescription, TimePeriod, Value) %>% 
  mutate(Value = as.numeric(Value))

goal15 <- goal15 %>% 
  select(GeoAreaName, SeriesDescription, TimePeriod, Value) %>% 
  mutate(Value = as.numeric(Value))

goal16 <- goal16 %>% 
  select(GeoAreaName, SeriesDescription, TimePeriod, Value) %>% 
  mutate(Value = as.numeric(Value))

goal17 <- goal17 %>% 
  select(GeoAreaName, SeriesDescription, TimePeriod, Value) %>% 
  mutate(Value = as.numeric(Value))

```



Join all data 

```{r}
goal1_2 <- full_join(goal1, goal2)
goal1_3 <- full_join(goal1_2, goal3)
goal1_4 <- full_join(goal1_3, goal4)
goal1_5 <- full_join(goal1_4, goal5)
goal1_6 <- full_join(goal1_5, goal6)
goal1_7 <- full_join(goal1_6, goal7)
goal1_8 <- full_join(goal1_7, goal8)
goal1_9 <- full_join(goal1_8, goal9)
goal1_10 <- full_join(goal1_9, goal10)
goal1_11 <- full_join(goal1_10, goal11)
goal1_12 <- full_join(goal1_11, goal12)
goal1_13 <- full_join(goal1_12, goal13)
goal1_14 <- full_join(goal1_13, goal14)
goal1_15 <- full_join(goal1_14, goal15)
goal1_16 <- full_join(goal1_15, goal16)
goal1_17 <- full_join(goal1_16, goal17)

```


```{r}
goal1_17 <- goal1_17 %>% 
  drop_na(Value)
```

```{r}
goal1_17_tidy_grouped <- goal1_17 %>% 
  group_by(SeriesDescription, GeoAreaName, TimePeriod) %>% 
  summarise(Value = mean(Value, na.rm = TRUE))
```

```{r}
goal1_17_tidy_grouped_most_recent <- goal1_17_tidy_grouped %>% 
  group_by(SeriesDescription, GeoAreaName) %>% 
  slice(which.max(TimePeriod))
```


```{r}
time_df <- goal1_17_tidy_grouped_most_recent %>% 
  group_by(GeoAreaName, TimePeriod) %>% 
  count()
```

```{r}
AIS <- c("Comoros", "Guinea-Bissau", "Maldives", "Mauritius", 
         "Sao Tome and Principe", "Seychelles", "Singapore", "Cabo Verde" )
```


```{r}
Carribean <- c("Antigua and Barbuda", "Bahamas", "Barbados", "Belize", 
               "Cuba", "Dominica", "Dominican Republic", "Grenada", "Guyana", "Haiti", "Jamaica", "Saint Kitts and Nevis", "Saint Lucia", 
           "Saint Vincent and the Grenadines", "Suriname", "Trinidad and Tobago", "Anguilla", "Aruba", "British Virgin Islands", "Curaçao", "Montserrat", "Puerto Rico", "Sint Maarten (Dutch part)", "British Virgin Islands", "Bonaire, Sint Eustatius and Saba", "United States Virgin Islands")
```


```{r}
Pacific <- c("Fiji", "Kiribati", "Marshall Islands", "Micronesia (Federated States of)", "Nauru", "Palau", "Papua New Guinea", 
 "Samoa", "Solomon Islands", "Timor-Leste", "Tonga", "Tuvalu", "Vanuatu",    "American Samoa", "Northern Mariana Islands", "Cook Islands", "French Polynesia", "Guam", "New Caledonia", "Niue")
```


```{r}
time_df <- time_df %>% 
  mutate(region = case_when(
    GeoAreaName %in% AIS ~ "AIS",
    GeoAreaName %in% Carribean ~ "Carribean", 
    GeoAreaName %in% Pacific ~ "Pacific"))
```

```{r}
time_df <- time_df %>% 
  filter(GeoAreaName != "Small island developing States (SIDS)")
```

```{r}
time_df$GeoAreaName <- gsub(" ", "_", time_df$GeoAreaName)
```

```{r}
data <- time_df
```


```{r}
write_csv(data, here("na_analysis/data/most_recent_year.csv"))
```



```{r}
empty_bar <- 2
nObsType <- nlevels(as.factor(data$TimePeriod))
to_add <- data.frame( matrix(NA, empty_bar*nlevels(data$region)*nObsType, ncol(data)) )
colnames(to_add) <- colnames(data)
to_add$region <- rep(levels(data$region), each=empty_bar*nObsType)

# data <- rbind(data, to_add)
data <- data %>% arrange(region, GeoAreaName)
# data$id <- rep( seq(1, nrow(data)/nObsType) , each=nObsType)

data$id <- data %>% group_indices(GeoAreaName)

data <- data %>%
  mutate(TimePeriod = as.character(TimePeriod))

# data <- data %>% arrange(region)



# Get the name and the y position of each label
label_data <- data %>% group_by(id, GeoAreaName) %>% summarize(tot=sum(n))
number_of_bar <- nrow(label_data)
angle <- 90 - 360 * (label_data$id-0.5) /number_of_bar     # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
label_data$hjust <- ifelse( angle < -90, 1, 0)
label_data$angle <- ifelse(angle < -90, angle+180, angle)
 
# prepare a data frame for base lines
base_data <- data %>% 
  group_by(region) %>% 
  summarize(start=min(id), end=max(id) - empty_bar) %>% 
  rowwise() %>% 
  mutate(title=mean(c(start, end)))
 
# prepare a data frame for grid (scales)
grid_data <- base_data
grid_data$end <- grid_data$end[ c( nrow(grid_data), 1:nrow(grid_data)-1)] + 1
grid_data$start <- grid_data$start - 1
grid_data <- grid_data[-1,]

```



```{r}
# Make the plot
p <- ggplot(data) +

# p$data <- p$data %>% 
#   select(-.group)
# 
# c <- p+      
  
  # Add the stacked bar
  geom_bar(aes(x=as.factor(id), y=n, fill=TimePeriod), stat="identity", alpha=0.5) +
  scale_fill_viridis(discrete = TRUE) +
  
  #Add a val=100/75/50/25 lines. I do it at the beginning to make sur barplots are OVER it.
  geom_segment(data=grid_data, aes(x = end, y = 0, xend = start, yend = 0), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 50, xend = start, yend = 50), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 100, xend = start, yend = 100), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 150, xend = start, yend = 150), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 200, xend = start, yend = 200), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +

  # # Add text showing the value of each 100/75/50/25 lines
  # ggplot2::annotate("text", x = rep(max(data$id),5), y = c(0, 50, 100, 150, 200), label = c("0", "50", "100", "150", "200") , color="grey", size=6 , angle=0, fontface="bold", hjust=1) +

  ylim(-150,max(label_data$tot, na.rm=T)) +
  theme_minimal() +
  theme(
    legend.position = "right",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-1,4), "cm")
  ) +
  coord_polar() +
  
  # Add labels on top of each bar
  geom_text(data=label_data, aes(x=id, y=tot+10, label=GeoAreaName, hjust=hjust), color="black", fontface="bold",alpha=0.6, size=2.5, angle= label_data$angle, inherit.aes = FALSE ) +
  
  # Add base line information
  geom_segment(data=base_data, aes(x = start, y = -5, xend = end, yend = -5), colour = "black", alpha=0.8, size=0.6 , inherit.aes = FALSE )  #+
  # geom_text(data=base_data, aes(x = title, y = -18, label=region), hjust=c(1,0,0), colour = "black", alpha=0.8, size=4, fontface="bold", inherit.aes = FALSE)

p
# Save at png
#ggsave(p, file="output.png", width=10, height=10)
```


```{r}
empty_bar <- 0

nObsType <- nlevels(as.factor(data$TimePeriod))

to_add <- data.frame( matrix(NA, empty_bar*nlevels(data$region)*nObsType, ncol(data)))

colnames(to_add) <- colnames(data)

to_add$region <- rep(levels(data$region), each=empty_bar*nObsType )

to_add$GeoAreaName <- as.character(to_add$GeoAreaName)


data <- rbind(data, to_add)

data <- data %>% arrange(region, GeoAreaName)

data <- as.data.frame(data)

data$id <- NA

data$id <- as.numeric(data$id)


data$id <- data %>% group_indices(GeoAreaName)

data <- data %>% arrange(region)



```


```{r}
# Get the name and the y position of each label
label_data <- data %>% group_by(id, GeoAreaName) %>% summarize(tot=sum(n))
number_of_bar <- nrow(label_data)
angle <- 90 - 360 * (label_data$id-0.5) /number_of_bar     # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
label_data$hjust <- ifelse( angle < -90, 1, 0)
label_data$angle <- ifelse(angle < -90, angle+180, angle)
 
# prepare a data frame for base lines
base_data <- data %>% 
  group_by(region) %>% 
  summarize(start=min(id), end=max(id) - empty_bar) %>% 
  rowwise() %>% 
  mutate(title=mean(c(start, end)))
 
# prepare a data frame for grid (scales)
grid_data <- base_data
grid_data$end <- grid_data$end[ c( nrow(grid_data), 1:nrow(grid_data)-1)] + 1
grid_data$start <- grid_data$start - 1
grid_data <- grid_data[-1,]


```







```{r}
p <- ggplot(data) +

# p$data <- p$data %>% 
#   select(-.group)
# 
# c <- p+      
  
  # Add the stacked bar
  geom_bar(aes(x=as.factor(id), y=n, fill=TimePeriod), stat="identity", alpha=0.5) +
  scale_fill_viridis(discrete = FALSE) +
  
  #Add a val=100/75/50/25 lines. I do it at the beginning to make sur barplots are OVER it.
  geom_segment(data=grid_data, aes(x = end, y = 0, xend = start, yend = 0), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 50, xend = start, yend = 50), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 100, xend = start, yend = 100), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 150, xend = start, yend = 150), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 200, xend = start, yend = 200), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +

  # # Add text showing the value of each 100/75/50/25 lines
  ggplot2::annotate("text", x = rep(max(data$id),5), y = c(0, 50, 100, 150, 200), label = c("0", "50", "100", "150", "200") , color="grey", size=6 , angle=0, fontface="bold", hjust=1) +

  ylim(-150,max(label_data$tot +50, na.rm=T)) +
  theme_minimal() +
  theme(
    legend.position = "right",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-1,4), "cm")
  ) +
  coord_polar() +
  
  ggtitle("Most Recent SDG Indicator Data for SIDS") +

  theme(
    plot.title=element_text( hjust=0.5, vjust=0, face='bold', margin=margin(t=40,b=-30))
  ) +
  
  # Add labels on top of each bar
  geom_text(data=label_data, aes(x=id, y=tot+10, label=GeoAreaName, hjust=hjust), color="black", fontface="bold",alpha=0.6, size=2.5, angle= label_data$angle, inherit.aes = TRUE) 
  
  # Add base line information
  # geom_segment(data=base_data, aes(x = start, y = -5, xend = end, yend = -5), colour = "black", alpha=0.8, size=0.6 , inherit.aes = FALSE )  #+
  # geom_text(data=base_data, aes(x = title, y = -18, label=region), hjust=c(1,0,0), colour = "black", alpha=0.8, size=4, fontface="bold", inherit.aes = FALSE)

p
```

